# Generated by Django 3.2.4 on 2024-03-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_enquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
