# Generated by Django 3.2.4 on 2024-03-14 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240314_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='email',
            new_name='mail',
        ),
    ]
