# Generated by Django 3.2.4 on 2024-03-15 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_adminprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
