# Generated by Django 3.2.4 on 2024-03-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20240317_1654'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
