# Generated by Django 3.2.4 on 2024-03-17 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
