# Generated by Django 3.2.4 on 2024-03-18 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
