# Generated by Django 3.2.4 on 2024-03-18 08:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0022_rename_userprofile_userprofiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfiles',
            new_name='Profile',
        ),
    ]
