# Generated by Django 3.2.4 on 2024-03-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_profile_usrprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usrprofile',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
